Repository liquibase/liquibase-cassandra, pull requests merged in 2024-05, with the labels that each got.

#293 chore: fix contributed builds
  .github/workflows/test.yml
Labels: skipReleaseNotes

#292 Fix #289: Add alternative execution for counting queries in lock service
  .gitignore
  src/main/java/liquibase/ext/cassandra/lockservice/LockServiceCassandra.java
Labels: TypeBug

#296 Fix/issue 289 (complement)
  src/main/java/liquibase/ext/cassandra/lockservice/LockServiceCassandra.java
Labels: TypeEnhancement
